#!/usr/bin/env python3
"""
cost_report.py — pull the governance views and emit a weekly cost digest.

Reads the curated GOVERNANCE.COST views (see /sql), ranks the top spenders and
optimization signals, and prints a plain-text digest suitable for email/Slack.

Usage:
    export SNOWFLAKE_ACCOUNT=...   SNOWFLAKE_USER=...
    export SNOWFLAKE_ROLE=COST_GOVERNANCE_RO
    export SNOWFLAKE_WAREHOUSE=WH_GOVERNANCE
    python cost_report.py            # uses external-browser / key-pair auth

Auth note: this script never hard-codes secrets. Prefer key-pair or SSO
(externalbrowser). Credentials come from the environment / connections.toml.
"""
from __future__ import annotations
import os
import sys

try:
    import snowflake.connector
except ImportError:
    sys.exit("pip install snowflake-connector-python")

QUERIES = {
    "Top 10 spenders (30d, credits)": """
        select user_name, round(sum(attributed_credits),1) as credits
        from governance.cost.v_credits_by_user
        where usage_date >= dateadd('day', -30, current_date())
        group by 1 order by credits desc limit 10
    """,
    "Right-sizing recommendations": """
        select warehouse_name, credits_30d, recommendation
        from governance.cost.v_wh_utilization
        where recommendation not like '%HEALTHY%'
        order by credits_30d desc
    """,
    "Idle-but-billing warehouses (7d)": """
        select warehouse_name, credits_7d, queries_7d
        from governance.cost.v_idle_warehouses order by credits_7d desc
    """,
    "Spend anomalies (>2 sigma)": """
        select usage_date, credits, z_score
        from governance.cost.v_spend_anomalies where flag = '🚨 SPIKE'
    """,
}


def connect():
    return snowflake.connector.connect(
        account=os.environ["SNOWFLAKE_ACCOUNT"],
        user=os.environ["SNOWFLAKE_USER"],
        role=os.environ.get("SNOWFLAKE_ROLE", "COST_GOVERNANCE_RO"),
        warehouse=os.environ.get("SNOWFLAKE_WAREHOUSE", "WH_GOVERNANCE"),
        authenticator=os.environ.get("SNOWFLAKE_AUTH", "externalbrowser"),
    )


def main() -> None:
    print("=" * 68)
    print("  SNOWFLAKE WEEKLY COST DIGEST")
    print("=" * 68)
    with connect() as conn, conn.cursor() as cur:
        for title, sql in QUERIES.items():
            print(f"\n### {title}")
            cur.execute(sql)
            rows = cur.fetchall()
            if not rows:
                print("   (nothing flagged — clean week ✅)")
                continue
            cols = [c[0] for c in cur.description]
            print("   " + " | ".join(cols))
            for r in rows:
                print("   " + " | ".join(str(x) for x in r))
    print("\nGenerated by snowflake-cost-governance ·", os.path.basename(__file__))


if __name__ == "__main__":
    main()
